### ISSUE TITLE
How to  run 

### ISSUE THREAD

**Issue by aamirshafique** [bjmorgan/vasppy#2]
Hi,
I am new user of vasp , i want to calculate the effective mass using your script
but i found an error when i run this script 
the error is message is
 ./effective_mass.py  [-h] -k  [0.00, 0.00, 0.00] -b 12 [-f PROCAR] [-v]
effective_mass.py: error: argument -k/--k-points: invalid int value: '[0.00,'
please tell me what is the right way 
best Regards
Aamir Shafique

**Comment by bjmorgan** [comment]
Hi Aamir,

Can you send me the complete command you are using to run the script?

Thanks,

Ben

**Comment by aamirshafique** [comment]
Dear Ben,I run script like this  ./effective_mass.py [-h] -k [0.00, 0.00, 0.00] -b 12 [-f PROCAR] [-v]Best regards, Aamir Shafique 

Sent from Yahoo Mail on Android 
 
  On Mon, 9 May, 2016 at 10:22 pm, Benjamin Morgan<notifications@github.com> wrote:   Hi Aamir,

Can you send me the complete command you are using to run the script?

Thanks,

Ben

**Comment by bjmorgan** [comment]
The correct syntax is for `-k` to take a list of (integer) k-point indexes (see my earlier updated reply).

Also, the square brackets around [-f PROCAR] in the help text indicate an optional argument. If you want to explicitly process a specific PROCAR file (for example, in a different directory) the syntax becomes:

    effective_mass.py -k 1 2 -b 12 -f ./directory_name/PROCAR

**Comment by aamirshafique** [comment]
Dear Ben
I didn't found your earlier updated reply 
I am confuse in -k 1 2, what is the meaning of 1  and 2 
best regards 
Aamir Shafique

**Comment by bjmorgan** [comment]
`1 2` here would refer to the 1st and 2nd k-points in your `KPOINTS` file, used to calculate your band structure. e.g. if you want to calculate the effective mass at Gamma towards X, your band structure k-points might start:

    0.0 0.0 0.0
    0.0 0.0 0.05
    …

If you are using different k-points to calculate the effective mass, the different indices are listed after `-k`.

**Comment by aamirshafique** [comment]
Dear Ben
Thank you for your response.
I have choosen 100 points between gamma and X  of step 0.05 and valence maxima occur at k point of index 79. How many kpoints enough, from 79 to ? . 
best regards 
Aamir Shafique

**Comment by bjmorgan** [comment]
That is a very good question. The more points you have in the fit, the less numerical noise you will have in the calculated effective mass. On the other hand, as you move further from the band edge you will increasingly see deviations from parabolic behaviour, and the assumptions implied by the fit start to weaken.

I would start by comparing the values obtained using `78 79 80`, `78 79`, and `79 80`. You can also extend the sampled region to see how this affects your result, e.g. comparing `79 80`, `79 80 81`, `79 80 81 82` (the code solves directly for a parabola if you supply only two k-points, otherwise it performs a least-squares fit to the eigenvalue data).

**Comment by aamirshafique** [comment]
Dear Ben 
Thank for you reply,
Can you send me what algorithm you apply in calculating effective mass (computational theory )
and I have a question that I have take only points  highlighted in attachment  for calculating the effective mass of hole and electron. Is it correct ? or increase or decrese the points my points
Best regards
Aamir Shafique
![screenshot-2](https://cloud.githubusercontent.com/assets/19266622/15175619/2716d67c-17a2-11e6-8c76-c2909b44c668.png)

**Comment by bjmorgan** [comment]
[effective_mass_theory.pdf](https://github.com/bjmorgan/vasppy/files/259103/effective_mass_theory.pdf)

Regarding the range of points to use for the effective mass calculation, I would use only a few points about the band edge (maybe just three or five). Your bands become less parabolic as Δk increases, and the effective mass is more clearly defined in the limit Δk → 0.

**Comment by aamirshafique** [comment]
Dear Ben
Thanks
The region I have selected for the calculating effective masses in x -direction is correct or not.
Best regards 
Aamir Shafique

**Comment by bjmorgan** [comment]
It's not a question of "correct" versus "incorrect" as there is no unique answer. For infinite accuracy calculations, the effective mass calculation would only use the points closest to the band edge. Fitting to more points decreases numerical errors, but the "effective mass" is now less well defined.

It is common to only use one or two k-points around the band edge. My advice would be to use points `78 79 80`, as in my previous reply.
