### ISSUE TITLE
string comparisons in species_from_strings

### ISSUE THREAD

**Issue by cajfisher** [bjmorgan/vasppy#20]
In rdf.py, RadialDistributionFunction -> species_from_strings,
the string comparison is currently done using "is", but this will not work when species names are provided as string variables because "is" actually compares object ids rather than the contents of the strings. It is safer to use "==".

        indices_i = [i for i, site in
                  #    enumerate(structures[0]) if site.species_string is species_i]
                      enumerate(structures[0]) if site.species_string == species_i]
         if species_j:
             indices_j = [j for j, site in
                       #   enumerate(structures[0]) if site.species_string is species_j]
                          enumerate(structures[0]) if site.species_string == species_j]

**Comment by bjmorgan** [comment]
Thank you for raising this issue. Can you please provide a minimal example that fails with the existing implementation?

**Comment by cajfisher** [comment]
This script brings up the error listed below (due to empty species_i list) when run on Fedora 31 system with Python 3.8.3 reading in a typical XDATCAR file (attached). Single-character element symbols appear to be found properly, but not two-character symbols, e.g., Na.

---------------------------------------------------------------------------
import sys, getopt, os
from pymatgen.io.vasp import Xdatcar
from vasppy import rdf
from os import path

# The main function
def main(argv):
   # Default values
    infile = 'XDATCAR' # Default file name

    try:
        opts, args = getopt.getopt(sys.argv[1:], "a:")
    except getopt.GetoptError:
        print('{} -a <species1>'.format(argv[0]))
        sys.exit(2)

    for opt, arg in opts:
        if opt == "-a":
            species1 = arg

    """
    # Read structure from XDATCAR file
    """
    xd = Xdatcar(infile)
    structures = xd.structures
    rdf_data = rdf.RadialDistributionFunction.from_species_strings(structures = structures,
                                                species_i = species1, species_j = species1)

if __name__ == '__main__':
    main(sys.argv[:])

--------------------------------------------------------------------------------------------------------------
The empty species_i list gets passed down the line until the following error occurs:

Traceback (most recent call last):
  File "bin/rdf_test.py", line 29, in <module>
    main(sys.argv[:])
  File "bin/rdf_test.py", line 26, in main
    rdf_data = rdf.RadialDistributionFunction.from_species_strings(structures = structures,
  File "/home/guest/.conda/envs/pymatgen/lib/python3.8/site-packages/vasppy-0.7.1.0-py3.8.egg/vasppy/rdf.py", line 142, in from_species_strings
    return cls(structures=structures,
  File "/home/guest/.conda/envs/pymatgen/lib/python3.8/site-packages/vasppy-0.7.1.0-py3.8.egg/vasppy/rdf.py", line 71, in __init__
    all_dr_ij = dr_ij(structure=structure,
  File "/home/guest/.conda/envs/pymatgen/lib/python3.8/site-packages/vasppy-0.7.1.0-py3.8.egg/vasppy/utils.py", line 123, in dr_ij
    dr_ij = lattice.get_all_distances(i_frac_coords, j_frac_coords)
  File "/home/guest/.conda/envs/pymatgen/lib/python3.8/site-packages/pymatgen/core/lattice.py", line 1307, in get_all_distances
    v, d2 = pbc_shortest_vectors(self, fcoords1, fcoords2, return_d2=True)
  File "/home/guest/.conda/envs/pymatgen/lib/python3.8/site-packages/pymatgen/util/coord.py", line 206, in pbc_shortest_vectors
    return cuc.pbc_shortest_vectors(lattice, fcoords1, fcoords2, mask,
  File "coord_cython.pyx", line 109, in pymatgen.util.coord_cython.pbc_shortest_vectors
  File "stringsource", line 251, in View.MemoryView.array_cwrapper
  File "stringsource", line 153, in View.MemoryView.array.__cinit__
ValueError: Invalid shape in axis 0: 0.

*** BTW: Adding a test for valid (non-empty) species_i and species_j lists in from_species_strings would also be helpful for error detection.


________________________________
差出人: Benjamin Morgan ***@***.***>
送信日時: 2021年6月9日 19:44
宛先: bjmorgan/vasppy ***@***.***>
CC: ｸﾚｲｸﾞ･ﾌｨｯｼｬｰ ***@***.***>; Author ***@***.***>
件名: Re: [bjmorgan/vasppy] string comparisons in species_from_strings (#20)


Thank you for raising this issue. Can you please provide a minimal example that fails with the existing implementation?

**Comment by bjmorgan** [comment]
Can you please upload the XDATCAR that this fails for, and provide the command line arguments that work / do not work?

**Comment by cajfisher** [comment]
Sorry, I didn't upload the XDATCAR file correctly yesterday. Hopefully it is now attached with this message.

Running the RadialDistributionFunction.from_species_strings from the shell prompt works without problem, e.g.:

from vasppy import rdf
from pymatgen.io.vasp import Xdatcar
xd = Xdatcar("XDATCAR")
structures = xd.structures
species1="Na"
species2="O"
rdf_data = rdf.RadialDistributionFunction.from_species_strings(structures = structures, species_i = species1, species_j = species2)

This can also be run as a python script and no error occurs. Presumably this is because Python "cannibalizes" the memory used for species1 when reading in data from the XDATCAR file in order to optimize memory usage, so that the ids end up being the same. (There's some discussion on this on stackoverflow, and other places, e.g., https://stackoverflow.com/questions/15171695/whats-with-the-integer-cache-maintained-by-the-interpreter/15172182#15172182)

A problem arises when the function is accessed from a python script in which the species name or names are taken from user input (e.g., using getopt), I guess this because python keeps a separate memory address for the user variable in this case; consequently the object ids end up being different.

import sys, getopt
from pymatgen.io.vasp import Xdatcar
from vasppy import rdf

try:
    opts, args = getopt.getopt(sys.argv[1:], "a:b:")
except getopt.GetoptError:
    pass

for opt, arg in opts:
     if opt == "-a":
        species1 = arg
     if opt == "-b":
        species2 = arg

xd = Xdatcar('XDATCAR' )
structures = xd.structures
rdf_data = rdf.RadialDistributionFunction.from_species_strings(structures = structures,
                                            species_i = species1, species_j = species2)

[XDATCAR.gz](https://github.com/bjmorgan/vasppy/files/6635277/XDATCAR.gz)

**Comment by cajfisher** [comment]
Sorry, one of the lines in the second script came out garbled. It should be "a colon b colon" (no spaces) after sys.argv[1:]. The indenting has also been lost (sigh). Indents after try, except, for and if are needed.

**Comment by bjmorgan** [comment]
Addressed in https://github.com/bjmorgan/vasppy/pull/21
