### ISSUE TITLE
`Doscar` does not handle ISPIN = 1 calculations correctly.

### ISSUE THREAD

**Issue by alexsquires** [bjmorgan/vasppy#23]
`Doscar.tdos` dataframe is mislabeled (possibly incorrect) when setting `ispin=1`. For the same vasp calculation with ISPIN = 2 and ISPIN = 1, these are the dataframes returned by vasppy

![image](https://user-images.githubusercontent.com/22589426/128691993-7ba2cf17-e5d5-4664-8342-6f67906db829.png)

**Comment by bjmorgan** [comment]
The *same* calculation, or different calculations on the same system (one spin-polarised, the other non-spin-polarised)?

**Comment by alexsquires** [comment]
two different calculations on the same system (LiF).

**Comment by bjmorgan** [comment]
Is it possible to attach the two DOSCARs? (should these give the same result in both cases? In the output above the energies and integrated DOS appear different?)

**Comment by alexsquires** [comment]
Seems like they are too big. I could rerun with a coarse DOS?

**Comment by alexsquires** [comment]
> (should these give the same result in both cases? In the output above the energies and integrated DOS appear different?)

I would have assumed so (the only thing that changed between the two calculations was `ISPIN`)

**Comment by bjmorgan** [comment]
Would be nice to have a minimal example that I can e.g. write some proper tests against.

**Comment by alexsquires** [comment]
[DOSCAR_non_spin_polarised.txt](https://github.com/bjmorgan/vasppy/files/6953906/DOSCAR_non_spin_polarised.txt)
[DOSCAR_spin_polarised.txt](https://github.com/bjmorgan/vasppy/files/6953913/DOSCAR_spin_polarised.txt)

**Comment by bjmorgan** [comment]
@alexsquires I think this is fixed now in ecefd14b3f2de8658130f5f7d370f69099c3dd86 (currently only in the `doscar_nsp` branch). Can you please test?

**Comment by alexsquires** [comment]
Sorry for the late response, this does fix the initial issue.
