### ISSUE TITLE
problem to run 

### ISSUE THREAD

**Issue by SUN123RAY** [bjmorgan/vasppy#3]
I have installed vasppy. Then I have tried to use effectivemass script, but it shows 
effective_mass -k 1 2 -b 271 -f PROCAR
Traceback (most recent call last):
  File "/home/x_sdyuc/bin/effective_mass", line 3, in <module>
    from vasppy import procar
ImportError: No module named 'vasppy'
although I kept all in my bin.

**Comment by bjmorgan** [comment]
You need to check that `vasppy` is in your `$PYTHONPATH`. There are two ways to do this:

1. Install using `python3 setup.py install`.

or

2. Manually add `vasppy` to your `$PYTHONPATH` environment variable.
e.g. I have the top `vasppy` directory in `$HOME/source/` as `$HOME/source/vasppy`
and then in my `.bashrc` I have:
```
    PYTHONPATH=source/vasppy:$PYTHONPATH
    export PYTHONPATH
```

**Comment by SUN123RAY** [comment]
I did this
export PATH=/home/x_sudch/bin:$PATH
PYTHONPATH=/home/x_sudch/bin/vasppy:$PYTHONPATH
export PYTHONPATH
 since I have vasppy here "/home/x_sudch/bin/vasppy" and I have python 3.4.1

but still showing that
effective_mass -k 1 2 -b 271 -f PROCAR
Traceback (most recent call last):
  File "/home/x_sudch/bin/effective_mass", line 3, in <module>
    from vasppy import procar
ImportError: No module named 'vasppy'

**Comment by bjmorgan** [comment]
What do you get if you type
```
echo $PYTHONPATH
```
?

**Comment by SUN123RAY** [comment]
/home/x_sudch/bin/vasppy:/home/x_sudch/bin/vasppy:/home/x_sudch/bin/vasppy:/home/x_sudch/bin/vasppy:/home/x_sudch/bin/vasppy:/home/x_sudch/vasppy:/software/apps/ase/3.7.1.3184

**Comment by bjmorgan** [comment]
First, you have multiple `vasppy` entries in your `$PYTHONPATH`. This *shouldn't* affect things, as it should be reading the first matching entry, which appears to have the correct path. 

I still think your Python3 installation isn't picking up the path. Can you check by running `python3` to start an interactive prompt. Then try:
```
import vasppy
```
and
```
import sys
print(sys.path)
```

**Comment by SUN123RAY** [comment]
[x_sudch@triolith1 vasppy]$ python3
Python 3.4.1 (default, Sep 22 2014, 20:16:56)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import vasppy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'vasppy'
>>> import sys
>>> print (sys.path)
['', '/home/x_sudch/bin/vasppy',
'/software/apps/python/3.4.1/snic-1/lib/python34.zip',
'/software/apps/python/3.4.1/snic-1/lib/python3.4',
'/software/apps/python/3.4.1/snic-1/lib/python3.4/plat-linux',
'/software/apps/python/3.4.1/snic-1/lib/python3.4/lib-dynload',
'/software/apps/python/3.4.1/snic-1/lib/python3.4/site-packages']

**Comment by bjmorgan** [comment]
And can you check what is in /home/x_sudch/bin/vasppy ? Because it is in
your path, but you're not finding the module.

**Comment by SUN123RAY** [comment]
vasppy]$ ls
atom.py  configuration.py  grid.py      outcar.py  polyhedron.py  procar.py
 xdatcar.py
cell.py  doscar.py         __init__.py  pimaim.py  poscar.py      rdf.py

**Comment by bjmorgan** [comment]
You seem to be missing the root module directory. My `vasppy` directory contains:

```
vasppy] $ ls
build  dist  install.py  LICENSE.txt  MANIFEST  README.md  scripts  setup.cfg  setup.py  vasppy  vasppy.egg-info
```

and `vasppy/vasppy` contains the files you listed.

**Comment by SUN123RAY** [comment]
yes I have installed correctly
but when tried to use the script, it shows
effective_mass -k 1 2 -b 271 -f PROCAR
Traceback (most recent call last):
  File "/home/x_amiba/bin/effective_mass", line 27, in <module>
    pcar.read_from_file( args.procar )
  File
"/home/x_amiba/bin/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py",
line 60, in read_from_file
  File
"/home/x_amiba/bin/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py",
line 45, in parse_k_points
AssertionError

**Comment by bjmorgan** [comment]
That assertion checks that the number of k-points read from the PROCAR file is the same as the number of k-points listed at the top of the file.

Can you upload your PROCAR and INCAR for this calculation please?

**Comment by SUN123RAY** [comment]
hi sorry for delay.
here is the error message and also files attached here
Traceback (most recent call last):
  File "/home/x_amiba/bin/effective_mass", line 27, in <module>
    pcar.read_from_file( args.procar )
  File
"/home/x_amiba/bin/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py",
line 60, in read_from_file
    self.parse_k_points()
  File
"/home/x_amiba/bin/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py",
line 45, in parse_k_points
    assert( self.number_of_k_points == len( k_points ) )
AssertionError​
 PROCAR
<https://drive.google.com/file/d/0BxcSTZ6OnUVRdHNEWnJkdkhwVUE/view?usp=drive_web>
​

**Comment by bjmorgan** [comment]
The issue seems to be because you have negative k-point vectors, which are listed in your PROCAR as:
```
 k-point  130 :    0.00000000-0.11538462 0.11538462     weight = 0.00500000
 k-point  131 :    0.00000000-0.12820513 0.12820513     weight = 0.00500000
```
i.e. with no spacing between the k-vector components. This meant they were missed by my regular expression for parsing the PROCAR. I have pushed an updated version which (hopefully) fixes this. Please let me know if the latest commit works for you.

**Comment by SUN123RAY** [comment]
ok so I will get the updated version here https://github.com/bjmorgan/vasppy

**Comment by SUN123RAY** [comment]
yes I have tried but shows again
effective_mass -k 1 2 3 -b 271 -f PROCAR
Traceback (most recent call last):
  File "/home/x_amiba/bin/effective_mass", line 27, in <module>
    pcar.read_from_file( args.procar )
  File
"/home/x_amiba/bin/vasppy.git/trunk/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py",
line 63, in read_from_file
  File
"/home/x_amiba/bin/vasppy.git/trunk/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py",
line 48, in parse_k_points
AssertionError

**Comment by bjmorgan** [comment]
Thanks. This was an additional bug where the formatting in spin-polarised PROCARs wasn't being handled correctly. I have fixed this and pushed an update, and also checked your PROCAR can be read in correctly. If you upload your OUTCAR I can test the effective mass calculation (this is to read in the reciprocal lattice) which might also fall over for a spin-polarised calculation / has only been tested on spin-paired calculations before.

**Comment by SUN123RAY** [comment]
[OUTCAR.txt](https://github.com/bjmorgan/vasppy/files/346168/OUTCAR.txt)
here is OUTCAR

**Comment by SUN123RAY** [comment]
the updated one in "trunk" or in "tags/0.0.4" directory ?

**Comment by bjmorgan** [comment]
Thanks. I tested this, and (as I suspected) it crashes for the spin-polarised case. I'll have a look at this later and will update when I have a general case working.

**Comment by SUN123RAY** [comment]
ok thanks and please let me know when u will upload

**Comment by SUN123RAY** [comment]
yes it crashes 
Traceback (most recent call last):
  File "/home/x_amiba/bin/effective_mass", line 31, in <module>
    printing = args.verbose )
  File "/home/x_amiba/bin/vasppy.git/trunk/env/lib/python3.4/site-packages/vasppy-0.0.3-py3.4.egg/vasppy/procar.py", line 109, in effective_mass_calc
ValueError: total size of new array must be unchanged

**Comment by bjmorgan** [comment]
The latest version of the code now runs against your PROCAR and OUTCAR. The `effective_mass` script now takes an additional argument `-s` for specifying which spin channel you want to calculate the effective mass for. Please check that the effective mass result you get is reasonable as I haven't yet written proper tests for the new code.

**Comment by SUN123RAY** [comment]
how can use this another argument, e.g. if I want to calculate for spin 1,
then will it be like this
effective_mass -k 1 2 3 -b 271 -s  -f PROCAR ?

**Comment by bjmorgan** [comment]
`effective_mass -h`
```
usage: effective_mass.py [-h] -k K_POINTS [K_POINTS ...] -b BAND_INDEX
                         [-f PROCAR] [-v] [-o OUTCAR] [-s SPIN]

Calculate an effective mass from a VASP PROCAR using a fitted quadratic

optional arguments:
…
  -s SPIN, --spin SPIN  select spin channel (default 1 / non-spin-polarised)
```

So your case would be `effective_mass -k 1 2 3 -b 271 -s 1 -f PROCAR`

Your system looks to be spin paired, so when I tested it I got the same effective mass for both spin-up and spin-down.

**Comment by SUN123RAY** [comment]
so I got this value "-1.53242546152" is it average over 3 high symmetry
KPOINTS that I selected?
in the argument -k 1 2 3, is it means that its taking first 3 points
coordinate from KPOINTS file? or it is taking first 3 high symmetry points
coordinate? Since in my KPOINTS have specified like this:
  -0.5   0   0.5      ! L
  -0.5 0.5 0.5      ! M

  -0.5 0.5 0.5      ! M
  -0.5 0 0  ! A
so is it taking L,M,A or taking like L, M, and M again ?

And also if I want to calculate the effective mass in between L and M or M
and A, so in the argument can we do like that
-k 1 2 "for L and M" and -k 2 3 "for M and A"?

**Comment by bjmorgan** [comment]
Your first three k-points are (as listed in your OUTCAR):
```
 k-points in reciprocal lattice and weights: k-points along high symmetry lines
  -0.50000000  0.00000000  0.50000000       0.005
  -0.50000000  0.01282051  0.50000000       0.005
  -0.50000000  0.02564103  0.50000000       0.005
```
Selecting these k-points for the effective mass fitting means you are calculating the effective mass at L in the L → M direction.

Your KPOINTS file asks for 40 k-points along L → M, then 40 k-points along M → A. If you want the effective mass at M, you can either run:
`effective_mass -k 38 39 40 -b 271 -s  1 -f PROCAR` for M → L
or
`effective_mass -k 41 42 443 -b 271 -s  1 -f PROCAR` for M → A

**Comment by SUN123RAY** [comment]
thanks a lot again.
yes I have tested. And few things more, whats is the most convenient or
appropriate way to extract effective mass, means e.g. if I will choose 3
k-points (38 39 40) along M to L at M for 271 band , showing effective mass
of hole -77.556! but if I will choose 5 k-points (36 37 38 39 40) then
showing -18.838. Again in the band structure have seen more than one band
(269, 270 271) passing the same high symmetry point (M). And again if will
choose 3 k-points (38 39 40) along M to L at M for 270 band, then showing
0.508. So is it like that have to take average for more than one band ?

**Comment by bjmorgan** [comment]
Defining the effective mass as the local curvature of the bands implicitly assumes that close to the band edges the bands are nearly parabolic. I would tend to sample the smallest distance in k-space away from the high symmetry point, while watching numerical accuracy in the bands energies. In your case, fitting to more k-points probably takes you some distance from M, where the band will be increasingly non-parabolic (if it was exactly parabolic, you would get the same result for any number of k-points sampled). If you want more k-points to improve the fit quality, I would increase the k-point density close to your band edge, rather than sample out to larger distances in k-space. 

Looking at your band structure, if you are interested in the valence-band maximum, this is at k = -0.5 0.141 0.141, not at M, so I'm not clear why you are calculating the band curvature at M. Note you have secondary maxima at k = -0.141 0.0 0.0 and k = 0.0 0.141 -0.141.

**Comment by bjmorgan** [comment]
Closing this issue as the technical problem re: running the code has been fixed.

**Comment by SUN123RAY** [comment]
Can you please explain, what does it mean by this
/software/apps/python/3.4.1/snic-1/lib/python3.4/site-packages/numpy/lib/polynomial.py:588: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)

**Comment by bjmorgan** [comment]
It usually means the least-squares fitting routine is being fed data points that don't have data in them. What command generates this warning?

**Comment by SUN123RAY** [comment]
effective_mass -k 120 121 122 -b 272 -s 1 -f PROCAR
actually k-point 120, 121 has same coordinate 0, 0, 0 and same E value.

and one thing more just to make sure, "-/+" sign infront of effective mass
value, is because of the -ve /+ve slope? And also in some paper have seen,
this is reported with sign or without sign, like if the effective mass at
VBM edge -0.837, then can I say this is as "0.837m0", where m0 is m0 = 9.11
x 10-31 kg is the free electron rest mass?

**Comment by bjmorgan** [comment]
Points 120 and 121 are identical, so you only have two independent data points, but are trying to fit a quadratic formula with three unknowns. If you have more unknown parameters than points, you get the RankWarning warning from the Polyfit fitting routine.

For the effective mass, this is proportional to the *curvature* of the bands. A "negative" effective mass from the code corresponds to negative curvature d^2E/dk^2 < 0, which is what should happen at the valence band maximum. Reporting a positive value is fine as long as you note that this is then the *hole* effective mass: https://en.wikipedia.org/wiki/Effective_mass_(solid-state_physics)
