### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by alejandrogallo** [bjmorgan/vasppy#4]
Where could I find some documentation of how I can use the project?

**Comment by bjmorgan** [comment]
There is no documentation at present (this is on the list of things to do). I am happy to help if you have specific questions / provide documentation for specific features.

**Comment by alejandrogallo** [comment]
Hi, thanks, understood.

**Comment by bjmorgan** [comment]
You can plot `CHGCAR`s (and other VASP grid format files) using conventional visualisation programs, such as [VESTA](http://jp-minerals.org/vesta/en/).
